stages:
  - stage: Build
    displayName: Build stage
    jobs:  
    - job: Build
    - deployment: VMDeploy
      displayName: web
      pool:
        vmImage: 'ubuntu-latest'
      environment:
        name:  VM
        resourceType: VirtualMachine
        tags: web
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo my first deployment